//! 内嵌图片资源表，由 `tools/gen-assets.py` 按 `crates/ui/assets/images` 生成，请勿手工编辑。
//!
//! 键名即资源路径（`images/Blocks/Anvil.png` 等），界面用 `img("images/Blocks/Anvil.png")` 引用；
//! 查表见 `assets::Assets`。

#[rustfmt::skip]
pub static EMBEDDED: &[(&str, &[u8])] = &[
    ("images/Backgrounds/server_bg.png", include_bytes!("../../assets/images/Backgrounds/server_bg.png")),
    ("images/Blocks/Anvil.png", include_bytes!("../../assets/images/Blocks/Anvil.png")),
    ("images/Blocks/Cleanroom.png", include_bytes!("../../assets/images/Blocks/Cleanroom.png")),
    ("images/Blocks/CobbleStone.png", include_bytes!("../../assets/images/Blocks/CobbleStone.png")),
    ("images/Blocks/CommandBlock.png", include_bytes!("../../assets/images/Blocks/CommandBlock.png")),
    ("images/Blocks/Egg.png", include_bytes!("../../assets/images/Blocks/Egg.png")),
    ("images/Blocks/Fabric.png", include_bytes!("../../assets/images/Blocks/Fabric.png")),
    ("images/Blocks/GoldBlock.png", include_bytes!("../../assets/images/Blocks/GoldBlock.png")),
    ("images/Blocks/Grass.png", include_bytes!("../../assets/images/Blocks/Grass.png")),
    ("images/Blocks/GrassPath.png", include_bytes!("../../assets/images/Blocks/GrassPath.png")),
    ("images/Blocks/LabyMod.png", include_bytes!("../../assets/images/Blocks/LabyMod.png")),
    ("images/Blocks/NeoForge.png", include_bytes!("../../assets/images/Blocks/NeoForge.png")),
    ("images/Blocks/OptiFabric.png", include_bytes!("../../assets/images/Blocks/OptiFabric.png")),
    ("images/Blocks/Quilt.png", include_bytes!("../../assets/images/Blocks/Quilt.png")),
    ("images/Blocks/RedstoneBlock.png", include_bytes!("../../assets/images/Blocks/RedstoneBlock.png")),
    ("images/Blocks/RedstoneLampOff.png", include_bytes!("../../assets/images/Blocks/RedstoneLampOff.png")),
    ("images/Blocks/RedstoneLampOn.png", include_bytes!("../../assets/images/Blocks/RedstoneLampOn.png")),
    ("images/Heads/EasyTier.png", include_bytes!("../../assets/images/Heads/EasyTier.png")),
    ("images/Heads/Emperormummy.png", include_bytes!("../../assets/images/Heads/Emperormummy.png")),
    ("images/Heads/LTCat.jpg", include_bytes!("../../assets/images/Heads/LTCat.jpg")),
    ("images/Heads/Logo-CE.png", include_bytes!("../../assets/images/Heads/Logo-CE.png")),
    ("images/Heads/Logo.png", include_bytes!("../../assets/images/Heads/Logo.png")),
    ("images/Heads/PCL-Community.png", include_bytes!("../../assets/images/Heads/PCL-Community.png")),
    ("images/Heads/Pysio.jpg", include_bytes!("../../assets/images/Heads/Pysio.jpg")),
    ("images/Heads/Yunmoan.jpg", include_bytes!("../../assets/images/Heads/Yunmoan.jpg")),
    ("images/Heads/bangbang93.png", include_bytes!("../../assets/images/Heads/bangbang93.png")),
    ("images/Heads/wiki.png", include_bytes!("../../assets/images/Heads/wiki.png")),
    ("images/Heads/z0z0r4.png", include_bytes!("../../assets/images/Heads/z0z0r4.png")),
    ("images/Icons/A.png", include_bytes!("../../assets/images/Icons/A.png")),
    ("images/Icons/B.png", include_bytes!("../../assets/images/Icons/B.png")),
    ("images/Icons/DefaultServer.png", include_bytes!("../../assets/images/Icons/DefaultServer.png")),
    ("images/Icons/Disabled.png", include_bytes!("../../assets/images/Icons/Disabled.png")),
    ("images/Icons/Folder.png", include_bytes!("../../assets/images/Icons/Folder.png")),
    ("images/Icons/NoIcon.png", include_bytes!("../../assets/images/Icons/NoIcon.png")),
    ("images/Icons/R.png", include_bytes!("../../assets/images/Icons/R.png")),
    ("images/Icons/Unavailable.png", include_bytes!("../../assets/images/Icons/Unavailable.png")),
    ("images/Skins/Alex.png", include_bytes!("../../assets/images/Skins/Alex.png")),
    ("images/Skins/Ari.png", include_bytes!("../../assets/images/Skins/Ari.png")),
    ("images/Skins/Efe.png", include_bytes!("../../assets/images/Skins/Efe.png")),
    ("images/Skins/Kai.png", include_bytes!("../../assets/images/Skins/Kai.png")),
    ("images/Skins/Makena.png", include_bytes!("../../assets/images/Skins/Makena.png")),
    ("images/Skins/Noor.png", include_bytes!("../../assets/images/Skins/Noor.png")),
    ("images/Skins/Steve.png", include_bytes!("../../assets/images/Skins/Steve.png")),
    ("images/Skins/Sunny.png", include_bytes!("../../assets/images/Skins/Sunny.png")),
    ("images/Skins/Zuri.png", include_bytes!("../../assets/images/Skins/Zuri.png")),
    ("images/icon.ico", include_bytes!("../../assets/images/icon.ico")),
    ("images/icon.png", include_bytes!("../../assets/images/icon.png")),
];
